version: "3.9"
services:

  unodb_mysql:
    image: uno-mysql:latest
    hostname: unodb
    ports:
      - "3306:3306"

  unodb_mongodb:
    image: uno-mongodb:latest
    hostname: unodb
    ports:
      - "27017:27017"
  fileio:
    container_name: "fileio-service"
    build:
      context: ./PersistenceModel
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
  root:
    container_name: "root-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    depends_on:
      - fileio
      - unodb
    environment:
      - UI_TYPE=gui
      - DISPLAY=host.docker.internal:0
      - DATABASE_HOST=uno_mongodb:27017
      - DATABASE_HOST=uno_mysql:3306